### ISSUE TITLE
Not a Successful boot every time

### ISSUE THREAD

**Issue by Zonark** [OffBroadway/flippyboot-ipl#6]
SDboot
Dol-001 rev. E mobo (missing the sp2 port)

When powering on for the day. Device fails to boot displaying error codes (haven’t captured yet). 
have to power cycle three times before successful boot occurs.

one thing that has been removed was the battery so wasn’t sure if that may have something to do with it.

issue only occurs approximately every cold boot

everything is turned on config file.
File required is also on sd card.
It is hidden but I run into the same issue regardless.
Color hex is cc0000

sometimes it can’t find the files then errors doesn’t have a recheck it appears. 

cube is heavily modified but boots Pico successfully every time when using its IPL file. Utilizing the coldbootipl file appears to be causing the issue.

modifications are as follows:
added internal micro sd card reader to Dol-001 rev.E (the one without the sp2 slot and removed traces) via pin out on bottom of mobo 
All connectors have been removed (broadband gameboyplayer ports) power has been relocated av port has been removed only has digital out now)
Disc drive removed due to dead drive. 
Controller port trimmed reset switch relocated 

2032 battery has been removed

![030AE008-B70D-40EF-B465-FBA3F6635354](https://user-images.githubusercontent.com/42153163/193835912-8556f50b-717f-4e7a-b575-a78580166ce5.jpeg)

**Comment by trevor403** [comment]
I love the GameCube mini case! Nice mods...

Yes I just pushed an update that should fix faulty boots, sometimes memory is not allocated on 32 byte aligned boundaries and it causes device to fail to read.

The fix is in https://github.com/OffBroadway/flippyboot-ipl/tree/gcloader-update

I will be releasing that branch this week. Look out for v0.1.2

**Comment by Zonark** [comment]
> I love the GameCube mini case! Nice mods...
> 
> Yes I just pushed an update that should fix faulty boots, sometimes memory is not allocated on 32 byte aligned boundaries and it causes device to fail to read.
> 
> The fix is in https://github.com/OffBroadway/flippyboot-ipl/tree/gcloader-update
> 
> I will be releasing that branch this week. Look out for v0.1.2

Awesomeness looking forward to the update! Thanks case has taken a bit of tweaking (shout out to Brigus studios!)haha now I have a blueretro installed too and it it finally complete!
